FROM python:3.12-slim

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --upgrade -r /code/requirements.txt

COPY . .

CMD ["fastapi", "run", "app/main.py", "--proxy-headers", "--port", "80"]
