FROM python:3.12-slim

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --upgrade -r /code/requirements.txt

RUN python - <<EOF
import nltk
nltk.download("punkt", download_dir="/usr/local/share/nltk_data")
nltk.download("punkt_tab", download_dir="/usr/local/share/nltk_data")
EOF

COPY . .

COPY entrypoint.sh /code/entrypoint.sh
RUN chmod +x /code/entrypoint.sh

ENTRYPOINT ["/code/entrypoint.sh"]

CMD ["fastapi", "run", "app/main.py", "--proxy-headers", "--port", "8000"]
