[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.5",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.136.3",
    "google-genai>=2.8.0",
    "guardrails-ai-detect-jailbreak>=0.1.6",
    "guardrails-ai-llamaguard-7b>=0.1.0",
    "guardrails-ai-profanity-free>=0.1.0",
    "guardrails-ai-regex-match>=0.1.0",
    "guardrails-ai-restrict-to-topic>=0.1.0",
    "guardrails-ai-valid-length>=0.1.0",
    "langchain>=1.3.11",
    "langchain-text-splitters>=1.1.2",
    "llmlingua>=0.2.2",
    "pgvector>=0.4.2",
    "pwdlib[argon2]>=0.3.0",
    "pyjwt>=2.13.0",
    "pymupdf4llm>=1.27.2.3",
    "python-dotenv>=1.2.2",
    "python-multipart>=0.0.32",
    "redis>=8.0.0",
    "sqlmodel>=0.0.39",
]
